@startuml
set namespaceSeparator none
class "Údaj" {
}

class "Veřejný údaj" {
}

class "Datová sada" {
}

"Údaj" <|-- "Veřejný údaj"
"Veřejný údaj" -- "Datová sada" :  "je publikován v datové sadě"
@enduml
