@startuml
set namespaceSeparator none
class Kategorie {
  "Má platnost kategorie do": string
  "Má platnost kategorie od": string
  "Má identifikátor kategorie": string
  "Má název kategorie": string
}

class "Kategorie soukromoprávních uživatelů údajů" {
}

class "Ustanovení právního předpisu" {
}

class "Ústřední správní úřad" {
}

class "Orgán veřejné moci" {
}

Kategorie <|-- "Kategorie soukromoprávních uživatelů údajů"
"Orgán veřejné moci" <|-- "Ústřední správní úřad"
Kategorie -- "Ustanovení právního předpisu" :  "Je vymezena ustanovením"
Kategorie -- "Ustanovení právního předpisu" :  "složení vymezeno ustanovením"
Kategorie -- "Ústřední správní úřad" :  "Ohlašuje kategorii"
@enduml
