@startuml
set namespaceSeparator none
class Dokument {
}

class "Emailová adresa" {
}

class Distribuce {
  "název": text
}

class "Způsob získání údaje" {
}

class "Způsob sdílení údaje" {
}

class "Typ obsahu údaje" {
}

class "Sdílení údaje" {
}

class Pojem {
}

class "Informační systém veřejné správy" {
}

class "Datová sada" {
  "klíčové slovo": http://www.w3.org/1999/02/22-rdf-syntax-ns#langString
  popis: text
  "název​": text
}

class "Právní předpis" {
}

class "Téma EuroVoc" {
}

class Standard {
}

class "Kontaktní bod" {
  "jméno": text
}

class "Časový interval" {
  "datum konce": http://www.w3.org/2001/XMLSchema#date
  "datum začátku": http://www.w3.org/2001/XMLSchema#date
}

class Frekvence {
}

class "Datové téma" {
}

class Poskytovatel {
}

class "Série datových sad" {
}

class Katalog {
  "název​​": text
  "popis​": text
}

class "Datová služba" {
  "název​​​": text
}

class Zdroj {
}

class "Specifikace podmínek užití" {
  "Jména autorů díla": text
  "Jména autorů originální databáze": text
}

class "Typ média" {
}

class "Formát souboru" {
}

class Licence {
}

Distribuce -- "1..*" "Způsob získání údaje" :  "má způsob získání dat sdílených rozhraním"
Distribuce -- "1..1" "Způsob sdílení údaje" :  "má způsob sdílení rozhraním"
Distribuce -- "1..*" "Typ obsahu údaje" :  "má typ obsahu sdíleného rozhraním"
Distribuce -- "Sdílení údaje" :  "zprostředkovává sdílení"
Distribuce -- "1..1" "Specifikace podmínek užití" :  "Specifikace podmínek užití​"
Distribuce -- "Právní předpis" :  "příslušný právní předpis"
Distribuce -- "1..1" Zdroj :  "přístupové URL"
Distribuce -- "0..1" "Datová služba" :  "přístupová služba"
Distribuce -- "0..1" Zdroj :  "Strojově čitelné schéma souboru ke stažení"
Distribuce -- "0..1" "Typ média" :  "formát komprese"
Distribuce -- "0..1" "Typ média" :  "formát balíčku"
Distribuce -- "0..1" "Typ média" :  "typ média"
Distribuce -- "0..1" "Formát souboru" :  "formát souboru ke stažení"
Distribuce -- "0..1" Zdroj :  "Odkaz na stažení souboru"
"Sdílení údaje" -- "1..1" Pojem :  "odpovídající pojem"
"Sdílení údaje" -- "1..1" "Způsob získání údaje" :  "je získán způsobem"
"Sdílení údaje" -- "1..1" "Typ obsahu údaje" :  "je sdílen jako"
"Sdílení údaje" -- "1..1" "Způsob sdílení údaje" :  "je sdílen způsobem"
"Informační systém veřejné správy" "1..1" -- "1..*" "Datová sada" :  zahrnuje
"Datová sada" -- Pojem :  "týká se pojmu"
"Datová sada" -- Distribuce :  distribuce
"Datová sada" -- "Právní předpis" :  "příslušný právní předpis​"
"Datová sada" -- "Téma EuroVoc" :  "klasifikace dle EuroVoc"
"Datová sada" -- Standard :  specifikace
"Datová sada" -- "0..1" Dokument :  dokumentace
"Datová sada" -- "0..1" "Kontaktní bod" :  "kontaktní bod"
"Datová sada" -- "0..1" "Časový interval" :  "časové pokrytí"
"Datová sada" -- "0..1" Frekvence :  "periodicita aktualizace"
"Datová sada" -- "0..1" Poskytovatel :  poskytovatel
"Datová sada" -- "0..1" "Série datových sad" :  "je součástí"
"Kontaktní bod" -- "0..1" "Emailová adresa" :  email
Katalog -- "Datová sada" :  "datová sada"
Katalog -- "0..1" Dokument :  "domovská stránka"
Katalog -- "0..1" "Kontaktní bod" :  "kontaktní bod​"
Katalog -- "1..1" Poskytovatel :  "poskytovatel​"
"Datová služba" -- "0..1" Dokument :  "dokumentace​"
"Datová služba" -- Standard :  "specifikace​"
"Datová služba" -- "0..1" Zdroj :  "popis přístupového bodu služby"
"Datová služba" -- "1..1" Zdroj :  "přístupový bod služby"
"Datová služba" -- "Právní předpis" :  "příslušný právní předpis​​"
"Specifikace podmínek užití" -- "0..1" Licence :  "Osobní údaje"
"Specifikace podmínek užití" -- "0..1" Licence :  "Zvláštní právo pořizovatele databáze"
"Specifikace podmínek užití" -- "0..1" Licence :  "Autorské dílo"
"Specifikace podmínek užití" -- "0..1" Licence :  "Originální databáze"
@enduml
