@startuml
set namespaceSeparator none
class Dokument {
  "číslo jednací": string
  "k rukám": string
  "stručný obsah dokumentu": text
}

class "Jednoznačný identifikátor" {
  "řetězcová podoba jednoznačného identifikátoru": string
}

class Spis {
  "Spisová značka": string
}

class "Evidenční číslo ze samostatné evidence dokumentů" {
  "řetězcová podoba evidenčního čísla": string
}

class "Elektronický dokument" {
}

class "Osoba ve vztahu k dokumentu" {
}

class "Dokument​" {
}

class "Dokument veřejnoprávního původce" {
  "číslo jednací​": string
}

class "Jednoznačný identifikátor​" {
}

class "Spis​" {
  "spisová značka": string
}

class "Evidenční číslo ze samostatné evidence dokumentů​" {
}

Dokument <|-- "Elektronický dokument"
Dokument <|-- "Dokument​"
"Dokument​" <|-- "Dokument veřejnoprávního původce"
"Jednoznačný identifikátor" <|-- "Jednoznačný identifikátor​"
"Evidenční číslo ze samostatné evidence dokumentů" <|-- "Evidenční číslo ze samostatné evidence dokumentů​"
Dokument -- "1..1" "Jednoznačný identifikátor" :  "je opatřen identifikátorem"
Dokument -- "0..1" Spis :  "je zařazen do spisu"
Dokument -- "0..1" "Evidenční číslo ze samostatné evidence dokumentů" :  "má evidenční číslo ze samostatné evidence dokumentů"
Dokument -- "0..1" Dokument :  "je odpovědí na dokument"
"Elektronický dokument" -- "1..1" "Osoba ve vztahu k dokumentu" :  "odesílatel"
"Elektronický dokument" -- "0..1" "Osoba ve vztahu k dokumentu" :  "příjemce"
"Dokument veřejnoprávního původce" -- "1..1" "Jednoznačný identifikátor​" :  "je opatřen identifikátorem​"
"Dokument veřejnoprávního původce" -- "0..1" "Spis​" :  "je zařazen do spisu​"
"Dokument veřejnoprávního původce" -- "0..1" "Evidenční číslo ze samostatné evidence dokumentů​" :  "má evidenční číslo ze samostatné evidence dokumentů​"
@enduml
