@startuml
set namespaceSeparator none
class "Místo" {
  "adresa neevidovaná v RÚIAN": string
}

class adresa {
}

class "Zahraniční adresa" {
}

class "Lokalizace popisem" {
  "lokalizační popis": string
}

class "adresní místo" {
  "kód adresního místa": string
}

class "Právnická osoba" {
  "obchodní firma": string
}

class "Fyzická osoba" {
}

class "Podnikající fyzická osoba" {
}

class Osoba {
  "identifikační číslo osoby": string
}

class "Právnická osoba​" {
  "číslo pro účely spotřebních daní": string
  "registrační a identifikační číslo hospodářských subjektů (EORI)": string
  "jedinečný identifikátor právnické osoby vytvořený odesílajícím členským státem": string
  "identifikační kód 2009/101/ES": string
  "identifikační kód právnické osoby": string
  "současná adresa právnické osoby": string
  "současný oficiální název": string
  "daňové registrační číslo": string
  "identifikační číslo pro účely DPH": string
}

class "Právnická osoba​​" {
}

class "Datová schránka" {
  "Má identifikátor datové schránky": string
}

class "Sídlo" {
}

class "Místo​" {
}

class "Fyzická osoba​" {
  "další jméno fyzické osoby": string
  "jméno fyzické osoby": string
  "příjmení fyzické osoby": string
}

class "Fyzická osoba​​" {
  "datum narození": date
  "jedinečný identifikátor fyzické osoby vytvořený odesílajícím členským státem": string
  "současné jméno (jména)": string
  "současné (současná) příjmení": string
  "současná adresa fyzické osoby": string
  "jméno (jména) a příjmení při narození": string
  "místo narození": string
  "pohlaví": string
}

class "Bydliště fyzické osoby" {
}

class Podnikatel {
  "dodatky charakterizující blíže osobu podnikatele nebo obchodní závod": text
  "obchodní firma​": string
}

class "Zapsaná fyzická osoba" {
}

class "Fyzická osoba​​​" {
}

class "Zapsaná osoba" {
}

class "Zapsaná fyzická osoba která je podnikatelem" {
}

class "Osoba ve vztahu k dokumentu" {
}

class "Právnická osoba jako osoba ve vztahu k dokumentu" {
}

class "Fyzická osoba jako osoba ve vztahu k dokumentu" {
}

class "Podnikající fyzická osoba jako osoba ve vztahu k dokumentu" {
}

class "Podnikající fyzická osoba zapsaná v obchodním rejstříku jako osoba ve vztahu k dokumentu" {
}

class "Podnikající fyzická osoba nezapsaná v obchodním rejstříku jako osoba ve vztahu k dokumentu" {
}

class "Fyzická osoba identifikovaná skrz eIDAS jako osoba ve vztahu k dokumentu" {
}

class "Právnická osoba identifikovaná skrz eIDAS jako osoba ve vztahu k dokumentu" {
}

"Lokalizace popisem" <|-- "Zahraniční adresa"
Osoba <|-- "Právnická osoba"
"Právnická osoba​" <|-- "Právnická osoba"
"Právnická osoba​​" <|-- "Právnická osoba"
"Fyzická osoba​" <|-- "Fyzická osoba"
"Fyzická osoba​​" <|-- "Fyzická osoba"
"Zapsaná fyzická osoba která je podnikatelem" <|-- "Podnikající fyzická osoba"
"Místo" <|-- "Místo​"
Podnikatel <|-- "Zapsaná fyzická osoba"
"Fyzická osoba​​​" <|-- "Zapsaná fyzická osoba"
"Zapsaná osoba" <|-- "Zapsaná fyzická osoba"
"Fyzická osoba" <|-- "Fyzická osoba​​​"
Osoba <|-- "Zapsaná osoba"
"Zapsaná fyzická osoba" <|-- "Zapsaná fyzická osoba která je podnikatelem"
"Osoba ve vztahu k dokumentu" <|-- "Právnická osoba jako osoba ve vztahu k dokumentu"
"Právnická osoba" <|-- "Právnická osoba jako osoba ve vztahu k dokumentu"
"Osoba ve vztahu k dokumentu" <|-- "Fyzická osoba jako osoba ve vztahu k dokumentu"
"Fyzická osoba" <|-- "Fyzická osoba jako osoba ve vztahu k dokumentu"
"Osoba ve vztahu k dokumentu" <|-- "Podnikající fyzická osoba jako osoba ve vztahu k dokumentu"
"Podnikající fyzická osoba" <|-- "Podnikající fyzická osoba jako osoba ve vztahu k dokumentu"
"Podnikající fyzická osoba jako osoba ve vztahu k dokumentu" <|-- "Podnikající fyzická osoba zapsaná v obchodním rejstříku jako osoba ve vztahu k dokumentu"
"Podnikající fyzická osoba jako osoba ve vztahu k dokumentu" <|-- "Podnikající fyzická osoba nezapsaná v obchodním rejstříku jako osoba ve vztahu k dokumentu"
"Fyzická osoba​​" <|-- "Fyzická osoba identifikovaná skrz eIDAS jako osoba ve vztahu k dokumentu"
"Osoba ve vztahu k dokumentu" <|-- "Fyzická osoba identifikovaná skrz eIDAS jako osoba ve vztahu k dokumentu"
"Právnická osoba​" <|-- "Právnická osoba identifikovaná skrz eIDAS jako osoba ve vztahu k dokumentu"
"Osoba ve vztahu k dokumentu" <|-- "Právnická osoba identifikovaná skrz eIDAS jako osoba ve vztahu k dokumentu"
"Místo" -- "1..1" adresa :  "má adresu"
"Místo" -- "1..1" "Zahraniční adresa" :  "má zahraniční adresu"
adresa -- "1..1" "adresní místo" :  "má adresu​"
"adresní místo" -- Osoba :  "Má adresu sídla osoby"
"Fyzická osoba" -- "0..1" "Datová schránka" :  "má datovou schránku fyzické osoby"
Osoba "0..1" -- "1..1" "Datová schránka" :  "Má datovou schránku osoby"
"Právnická osoba​​" "1..*" -- "1..1" "Sídlo" :  "Má sídlo právnické osoby"
"Sídlo" -- "1..1" "Místo​" :  "má místo sídla"
"Místo​" "1..1" -- "Bydliště fyzické osoby" :  "má místo bydliště"
"Místo​" "0..1" -- "Osoba ve vztahu k dokumentu" :  "doručovací místo"
"Fyzická osoba​" "1..*" -- "1..1" "Bydliště fyzické osoby" :  "má bydliště fyzické osoby"
@enduml
