@startuml
set namespaceSeparator none
class "Identifikátor specifického omezení" {
  "kód identifikátoru specifického omezení": string
  "název identifikátoru specifického omezení": text
  "popis identifikátoru specifického omezení": text
}

@enduml
