@startuml
set namespaceSeparator none
class "Obecní úřad" {
  "identifikační číslo osoby": http://www.w3.org/2001/XMLSchema#string
}

class "Krajský úřad" {
  "identifikační číslo osoby​": http://www.w3.org/2001/XMLSchema#string
}

class "Sbírka listin" {
  "webová stránka sbírky listin": http://www.w3.org/2001/XMLSchema#anyURI
}

class "Vyšší územní samosprávní prvek" {
}

class "Datová schránka" {
  "Má identifikátor datové schránky": http://www.w3.org/2001/XMLSchema#string
}

class "Dobrovolný svazek obcí" {
  "identifikační číslo osoby​​": http://www.w3.org/2001/XMLSchema#string
  "Má adresu sídla osoby neevidovanou v RÚIAN": http://www.w3.org/2001/XMLSchema#string
  "Má název orgánu veřejné moci": http://www.w3.org/2000/01/rdf-schema#Literal
  "Má datum ukončení výkonu působnosti orgánu veřejné moci": http://www.w3.org/2001/XMLSchema#date
  "Má datum zahájení výkonu působnosti orgánu veřejné moci": http://www.w3.org/2001/XMLSchema#date
  "webová stránka svazku obcí": http://www.w3.org/2001/XMLSchema#anyURI
  "předmět činnosti svazku obcí": text
  "právní důvod zrušení svazku obcí": text
  "datum zrušení svazku obcí": http://www.w3.org/2001/XMLSchema#date
}

class "adresní místo" {
  "kód adresního místa": http://www.w3.org/2001/XMLSchema#anyURI
}

class "Zahraniční adresa" {
  "lokalizační popis": http://www.w3.org/2001/XMLSchema#string
}

class okres {
}

class "kraj 1960" {
}

class obec {
  "název obce": http://www.w3.org/2001/XMLSchema#string
}

class "Obec jako člen dobrovolného svazku obcí" {
  "den zániku členství": http://www.w3.org/2001/XMLSchema#date
  "den vzniku členství": http://www.w3.org/2001/XMLSchema#date
}

class adresa {
  "má kód adresního místa": http://www.w3.org/2001/XMLSchema#anyURI
}

class "Místo" {
  "adresa neevidovaná v RÚIAN": http://www.w3.org/2001/XMLSchema#string
}

class "Bydliště fyzické osoby" {
}

class "Fyzická osoba" {
  "příjmení fyzické osoby": http://www.w3.org/2001/XMLSchema#string
  "jméno fyzické osoby": http://www.w3.org/2001/XMLSchema#string
}

class "Funkce orgánu" {
  "název funkce": text
  "den zániku funkce": http://www.w3.org/2001/XMLSchema#date
  "den vzniku funkce": http://www.w3.org/2001/XMLSchema#date
}

class "Orgán" {
  "způsob jednání": text
  "název orgánu": text
}

class "Zdroj výčtu členů" {
}

class "Rejstřík svazků obcí" {
  "webová stránka rejstříku svazku obcí": http://www.w3.org/2001/XMLSchema#anyURI
}

"Obecní úřad" "1..1" -- "1..1" "Obec jako člen dobrovolného svazku obcí" :  "spravuje obec"
"Krajský úřad" -- "0..1" "Vyšší územní samosprávní prvek" :  "spravuje vyšší územní samosprávní prvek"
"Krajský úřad" "0..1" -- "1..1" "Rejstřík svazků obcí" :  "vede rejstřík svazků obcí"
"Dobrovolný svazek obcí" -- "0..1" "Datová schránka" :  "Má datovou schránku orgánu veřejné moci"
"Dobrovolný svazek obcí" -- "1..1" "adresní místo" :  "Má adresu sídla orgánu veřejné moci"
"Dobrovolný svazek obcí" "1..1" -- "0..1" "Sbírka listin" :  "eviduje sbírku listin"
"Dobrovolný svazek obcí" "1..1" -- "1..*" "Zdroj výčtu členů" :  "má zdroj výčtu členů"
"Dobrovolný svazek obcí" -- "Rejstřík svazků obcí" :  "je zapsán v rejstříku"
okres -- "0..1" "kraj 1960" :  "má nadřazený kraj 1960"
obec -- "0..1" okres :  "má nadřazený okres"
"Obec jako člen dobrovolného svazku obcí" "1..1" -- "1..1" obec :  "má území obce"
"Obec jako člen dobrovolného svazku obcí" "1..1" -- "Dobrovolný svazek obcí" :  "je členem dobrovolného svazku obcí"
"Místo" -- "1..1" adresa :  "má adresu"
"Místo" -- "1..1" "Zahraniční adresa" :  "má zahraniční adresu"
"Bydliště fyzické osoby" -- "0..1" "Místo" :  "má místo bydliště"
"Fyzická osoba" "1..*" -- "0..1" "Bydliště fyzické osoby" :  "má bydliště fyzické osoby"
"Funkce orgánu" -- "Fyzická osoba" :  "je vykonávána fyzickou osobou"
"Orgán" "1..1" -- "1..*" "Funkce orgánu" :  "obsahuje funkce"
"Orgán" -- "1..1" "Dobrovolný svazek obcí" :  "je orgánem svazku obcí"
@enduml
