name: Validator2

on:
  push:
  pull_request:
    branches:
    - master
    - develop
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Data validator
      uses: opendata-mvcr/data-validator/github@master
      with:
        configuration: file://./.github/workflows/validate-syntax.ttl
